queue_rules:
  - name: default
    queue_conditions:
      - base=master
      - label~=merge-queue|dependencies
    merge_conditions:
      - check-success=builds (cli-args, ubuntu-latest)
      - check-success=builds (ethermint, ubuntu-latest)
      - check-success=builds (mkgoenv, ubuntu-latest)
      - check-success=builds (vendored-modules, ubuntu-latest)
      - check-success=golangci-lint
      - check-success=gomod2nix_toml
      - check-success=list-jobs
      - check-success=nixpkgs-fmt
    merge_method: rebase

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
